### ISSUE TITLE
Bug: file content error with https

### ISSUE THREAD

**Issue by tian-le** [aria2/aria2#1012] opened 2017-09-22 13:24 UTC
Hi,
First of all, appreciate your great work. Aria2c is a great tool!
I noticed a bug with aria2 for years. When I try to download a large file (>500MB) with https protocol with http authentication, it is very likely (~50% cases) that there would be few bytes wrong in the downloaded file.
For example, I meet this issue again today. I used 64bit version of aria2c in Windows 7 SP1. The common I used is:
aria2c.exe -c -R --max-connection-per-server=5 --file-allocation=none --console-log-level=warn --check-certificate=false --http-user=<XXXX> --http-passwd=<XXXX> https://smpdl.sap-ag.de/~swdc/002007974700001465662017D/70SWPM10SP21_2-20009701.sar
The size of the file is 686,971,484 bytes. The file I got with aria2c is wrong starting from offset 0x26EC3EC8 to 0x26EC3F1C (85 bytes). The correct content should be:
0xF4693BB9539CDFB66AF87F2D4FE4D1B26A1CCDA6DAFD20D270CBDB7F99DD940A8EB0A4BC3AEE5E65FFC706C4754AC373223C008008DE7FAA3FD3FE43FD59C3D646D4C9C9DE49C2D0CEC4E63F8BCF2909FAD2D88228
The incorrect content is:
0x1503030050464BF8FCF81959BA757A26C24D673FD60100C7BD7A1E35DE76E8CCAA08571DB7DEAEEDBF24E2FB142B5C0EC91E50D6BF07D50CADDB0633B9D31A23381BCDFE277AD10D0D0D0D0D0D0D0D0D0D0D0D0D0D
I cannot reproduce this issue when downloading this file for the second time.
Similarly, there are also problems with these files:
---------------------
file:
https://smpdl.sap-ag.de/~swdc/002007974700001466622017D/SWPM10SP21_2-20009701.SAR
filesize: 634,163,019 bytes
incorrect part: 0x24A4FEC8-0x24A4FF1C
incorrect content:
0x15030300501F6058FA231F0EEB05A3B501DD26FC050100AEB82790630DF0D56A2EC4AF5143184C581D4DB8E30136E8AC2D2CE1B9CE7F217031D2E98D96874EDAB97445D5378DB00D0D0D0D0D0D0D0D0D0D0D0D0D0D
---------------------
file:
https://smpdl.sap-ag.de/~swdc/002007974700001465672017D/70SWPM10SP21_2-20009707.sar
filesize: 627,413,345 bytes
incorrect part: 0xE47BEC8-0xE47BF1C
incorrect content:
0x1503030050A5BF9613BFCFD82AF480CA5DCC35325B01008CF471ACDC911C0314206568C1F394E7D3235ADAE4009AE42F3BC004677A3C431FF5CFC10C04119B04DDDEAF37E4D1340D0D0D0D0D0D0D0D0D0D0D0D0D0D
---------------------
file:
https://smpdl.sap-ag.de/~swdc/002007974700001466672017D/SWPM10SP21_2-20009707.SAR
filesize: 774,572,460 bytes
incorrect part: 0x26F63EC8-0x26F63F1C
incorrect content:
0x1503030050DC2A5B59691B3531DF13BB5247850EB50100E7F1BF9613A7B1C4C5958119F3353C54ADA32CE8C93D2B677B0F33A9B377F5C37CE6BB14E7F4BBA1F333D8F8C3EBFC8E0D0D0D0D0D0D0D0D0D0D0D0D0D0D
---------------------
It can be seen the errors are always in offset xxxEC8 to xxxF1C (85 bytes), and the incorrect bytes are always 0x1503030050....0D0D0D0D0D0D0D0D0D0D0D0D0D0D. Could you please kindly check what cause this issue and kindly fix it?
Thanks!!!

**Comment by tian-le** [comment] 2017-09-22 23:20
The version I used yesterday is 1.32. However, I knew this issue from the first day I use aria2c, which was about 3.5 years ago and version was about 1.17. This issue never got fixed.

**Comment by tian-le** [comment] 2017-09-29 03:48
some clues:
1. The website doesn't support keep-alive connection. Please refer the response header as below.
[('Content-Type', 'application/x-sar'),
 ('Accept-Ranges', 'bytes'),
 ('Server', 'Microsoft-IIS/7.28'),
 ('Last-Modified', 'Thu, 28 Sep 2017 07:38:19 GMT'),
 ('Content-Length', '775031488'),
 ('Date', 'Fri, 29 Sep 2017 03:03:48 GMT'),
 ('Connection', 'close')]
2. Seems like the connection might be disconnected by the server. Please refer the messages in wget as below.
wget.exe -c --retry-connrefused --no-check-certificate --http-user=I060607 --htt
p-password=NTZZCV5A -i url.lst
--2017-09-29 12:22:58--  https://XXXXXXX:*password*@smpdl.sap-ag.de/~swdc/002007
974700001503242017D/SWPM10SP21_3-20009701.SAR
Resolving smpdl.sap-ag.de (smpdl.sap-ag.de)... 23.0.103.58
Connecting to smpdl.sap-ag.de (smpdl.sap-ag.de)|23.0.103.58|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized
Authentication selected: Basic realm="SAP Service Marketplace"
Connecting to smpdl.sap-ag.de (smpdl.sap-ag.de)|23.0.103.58|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 634398713 (605M) [application/x-sar]
Saving to: 'SWPM10SP21_3-20009701.SAR'

SWPM10SP21_3-200097  84%[===============>    ] 511.94M   512KB/s    in 74m 33s

2017-09-29 13:37:36 (117 KB/s) - Connection closed at byte 536805064. Retrying.

--2017-09-29 13:37:37--  (try: 2)  https://XXXXXXX:*password*@smpdl.sap-ag.de/~s
wdc/002007974700001503242017D/SWPM10SP21_3-20009701.SAR
Connecting to smpdl.sap-ag.de (smpdl.sap-ag.de)|23.0.103.58|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized
Authentication selected: Basic realm="SAP Service Marketplace"
Connecting to smpdl.sap-ag.de (smpdl.sap-ag.de)|23.0.103.58|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 634398713 (605M), 97593649 (93M) remaining [application/x-sar]
Saving to: 'SWPM10SP21_3-20009701.SAR'

10SP21_3-20009701.S  87%[++++++++++++++++>   ] 532.29M  43.6KB/s    eta 35m 20s

**Comment by tatsuhiro-t** [comment] 2017-09-29 12:36
I think aria2 should handle connection: close just fine.
If --max-connection-per-server=1 is used, is file downloaded fine?

**Comment by mostafa88** [comment] 2017-10-03 14:29
I think my problem is related to this issue.
Our server supports both http and https for downloading files.
When i try download a large file (about 1.4GB) with https, always 31 bytes in the file are different from the original file. As @tian-le  mentioned, the differents are in the specific pattern.
The start address of different in my case in 3 unsuccessfull downloads are the following list( 51269E2A,40461E57,4045DE57) that xxxxxExx.
I try to download with https and  "--max-connection-per-server=1", but the result is the same. And when I download with http, the file download completes without any problem.

You can download my test file from [here](https://api.ariogames.ir/fileuploader/static/games/e811c331751835ded597c8627faad52c/36cc40add8396f2ededd99b527fc4641/Murder%20In%20Tehran's%20Alleys%201933/Sound.dcp) with https.

**Tested on
-windows 10, 
-aria2c version 1.31.0 and 1.32.0

**Comment by tatsuhiro-t** [comment] 2017-10-03 14:35
Can downloading the file from the link reproduce this issue?

**Comment by mostafa88** [comment] 2017-10-03 14:52
@tatsuhiro-t: yes every time i download the file with aria2c on https, the file has some changes.
md5 of original file is: "4b81addf4d2c3b57ec729629608a52db"

**Comment by tatsuhiro-t** [comment] 2017-10-03 15:03
Thank you.  I will debug aria2c windows build using that server.

**Comment by tatsuhiro-t** [comment] 2017-10-07 10:40
It looks like aria2 wrote TLS encrypted data to a disk without decrypting it.
0x1503030050 is actually TLS record header:
0x15 = alert
0x0303 = protocol version (3,3) which means TLSv1.2
0x0050 = record length, which is 80 bytes.

**Comment by tatsuhiro-t** [comment] 2017-10-07 10:45
I hope #1021 fixes this issue.

**Comment by antbryan** [comment] 2017-10-19 04:04
@tian-le & @mostafa88, can you verify if aria2 1.33.0 fixes your issues?

https://github.com/aria2/aria2/releases/tag/release-1.33.0

**Comment by tian-le** [comment] 2017-10-19 04:08
@antbryan I downloaded a large file with https protocol yesterday and got no error. It seems like the error gets fixed. However, not too sure if the problem gets 100% resolved, as this issue doesn't always reproduce in the past.

**Comment by mebbert** [comment] 2017-10-21 22:19
@tatsuhiro-t 
I'm seeing what I think is the same issue on the linux version. I ran `aria2c -x 10 <link>`. The md5 did not match the md5 provided by the company. I'm using 1.32.0, but it looks like you only made a change for the windows version, right?

**Comment by tatsuhiro-t** [comment] 2017-10-22 03:59
The fix I made is windows specific, and if I understand correctly, it only occurs on Windows platform.
aria2 uses different TLS stack on Linux, and it does not produce same issue.

If you are experience corrupted downloads, it is probably the different issue. I think it would be better to open an new issue.

**Comment by mostafa88** [comment] 2018-01-17 09:01
@antbryan: the problem has fixed in version 1.33.1

Thanks

**Comment by tatsuhiro-t** [comment] 2018-01-17 15:42
Thank you for confirmation.

**Closed by tatsuhiro-t** 2018-01-17 15:42 UTC
Labels: win
